# ==========================================================================
# Title: ZhugePrajna Personal Dedicated "rust.cargo" Settings
# Date:  03 May 2024 07:21:00
# ==========================================================================
# Environment Settiings For "Install Rust":
#
# [For Windows]
# $ENV:RUSTUP_DIST_SERVER='https://mirrors.ustc.edu.cn/rust-static'
# $ENV:RUSTUP_UPDATE_ROOT='https://mirrors.ustc.edu.cn/rust-static/rustup'
# .\rustup-init.exe
#
# [For Linux]
# export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
# export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup
# source ~/.bashrc(~/.zshrc)
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# ==========================================================================
# Environment Settiings For "Cargo":
#
# [source.crates-io]
# registry = "https://github.com/rust-lang/crates.io-index"
#
# 指定镜像:
# replace-with = '镜像源名' (如: ustc)
# ==========================================================================
# cargo 1.68 版本开始支持稀疏索引:

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
